<?php

class WebApiContext extends \Behat\CommonContexts\WebApiContext
{

    /**
     * @return array
     */
    public function getHeaders()
    {
        return parent::getHeaders(); // TODO: Change the autogenerated stub
    }

}